name: txtpack
description: txtpack codec for dart
version: 1.2.3
homepage: https://github.com/itsabgr/dart-txtpack
environment:
  sdk: '>=2.15.0 <3.0.0'


dependencies:
  http: ^0.13.4
dev_dependencies:
  test: ^1.20.0
